-- ========================================================
-- SUPABASE DATABASE SETUP SCRIPT FOR TOTAL AQUA SOLUTION
-- ========================================================
-- Copy and paste this script into the Supabase SQL Editor
-- (Supabase Dashboard -> SQL Editor -> New Query -> Run)

-- 1. Create shop_config table
CREATE TABLE IF NOT EXISTS public.shop_config (
    id INTEGER PRIMARY KEY,
    shop_name TEXT NOT NULL,
    tagline TEXT,
    location TEXT,
    whatsapp TEXT,
    phone TEXT,
    address TEXT,
    hours TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert default shop config row
INSERT INTO public.shop_config (id, shop_name, tagline, location, whatsapp, phone, address, hours)
VALUES (
    1,
    'Total Aqua Solution',
    'Pure Water, Healthy Life',
    'Sikar (Rajasthan)',
    '917851039925',
    '+91 78510 39925',
    'Devipura Rd, near S. N, Bisayatiyan Mohalla, Sikar, Rajasthan 332001',
    '9:00 AM to 8:00 PM (All Days)'
) ON CONFLICT (id) DO NOTHING;

-- 3. Create products table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    price NUMERIC NOT NULL,
    original_price NUMERIC,
    badge TEXT,
    image TEXT,
    specs TEXT[] DEFAULT '{}'::text[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Insert default products
INSERT INTO public.products (brand, name, type, price, original_price, badge, image, specs)
VALUES 
('Kent', 'Kent Grand Plus', 'RO+UV+UF', 16500, 19500, 'Bestseller', '', ARRAY['TDS Controller', '9L Storage Tank', 'Save Water Technology', '1 Year Brand Warranty']),
('Kent', 'Kent Gold', 'UF', 3200, 3800, 'Non-Electric', '', ARRAY['Gravity Based Filtration', '20L Storage Tank', 'Food-Grade Plastic', '6 Months Warranty']),
('Aquaguard', 'Aquaguard Ritz', 'RO+UV', 18999, 22000, 'Copper Active', '', ARRAY['Alkaline Boost Tech', 'Active Copper Filter', 'Advanced MTDS Controller', '1 Year Warranty']),
('Aquaguard', 'Aquaguard Aura', 'UV+UF', 8499, 10500, 'Eco-Friendly', '', ARRAY['Active Copper Filter', 'Dual Filtration', 'Compact Design', '1 Year Brand Warranty']),
('Pureit', 'Pureit Copper+ Eco', 'RO+UV+UF', 21500, 24999, 'Premium', '', ARRAY['Copper Charge Technology', 'Eco Recovery (Save Water)', '8L Storage Tank', '1 Year Warranty']),
('Pureit', 'Pureit Classic', 'RO', 11999, 14500, 'Value for Money', '', ARRAY['TDS Modulator', '6L Storage Tank', 'Advanced 6-Stage Tech', '1 Year Brand Warranty']),
('Livpure', 'Livpure Bolt', 'RO+UV', 10499, 12999, 'Smart RO', '', ARRAY['7-Stage Filtration', '7L Storage Tank', 'Mineralizer', '1 Year Brand Warranty']),
('Livpure', 'Livpure Glitz', 'RO+UV+UF', 12499, 14999, 'Hot Seller', '', ARRAY['Alkaline Filter', 'Smart LED Indicators', '8L Storage Tank', '1 Year Warranty'])
ON CONFLICT (id) DO NOTHING;

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.shop_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 6. Policies for shop_config
CREATE POLICY "Allow public read-only access to shop_config"
ON public.shop_config FOR SELECT
USING (true);

CREATE POLICY "Allow authenticated users to update shop_config"
ON public.shop_config FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- 7. Policies for products
CREATE POLICY "Allow public read-only access to products"
ON public.products FOR SELECT
USING (true);

CREATE POLICY "Allow authenticated users to insert products"
ON public.products FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update products"
ON public.products FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete products"
ON public.products FOR DELETE
TO authenticated
USING (true);
